# task
base_config:
  - ../config_base.yaml
  - ../dataset_params.yaml

dataset_cls: from tasks.tts.dataset_utils import BaseSpeechDataset
model_cls: ""

#############
# dataset in training
#############
endless_ds: true
min_frames: 0
max_frames: 1548
frames_multiple: 1
max_input_tokens: 1550
ds_workers: 10

#########
# model
#########
use_spk_id: false
use_spk_embed: false
mel_losses: "l1:1.0" # "ssim:0.5|l1:0.5"

###########
# optimization
###########
lr: 0.0005
scheduler: noam # rsqrt|warmup|none|noam
warmup_updates: 4000
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.98
weight_decay: 0
clip_grad_norm: 1
clip_grad_value: 0

###########
# train and eval
###########
use_word_input: false
max_valid_sentences: 1
max_valid_tokens: 60000
valid_infer_interval: 10000
train_set_name: "train"
train_sets: ""
valid_set_name: "valid"
test_set_name: "test"
num_valid_plots: 5
test_ids: []
test_input_yaml: ""
vocoder_ckpt: ""
profile_infer: false
out_wav_norm: false
save_gt: false
save_f0: false
gen_dir_name: "test"

###########
# utils
###########
plot_f0: false
save_mel_npy: false
